# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b54388967305123c7cac64ec758c98394167332af43adf4a6b37b46ac97824483e4110a80e84190237b3d64803376ada078df7a2b6bfe007b60284a376bf26b

test:
  secret_key_base: 62181ce655b926ceb0b1dc0f2386797ad1693d1c1b7e45839bb3e89ea5261f1e65a9475d435888477004a09f5446822ea11ff4a9e966b3e7c0816cb1a042d00f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
